
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yu zi guan
 */
public class Employee_Main extends javax.swing.JFrame {
    
     public Employee_Main() {
        initComponents();
       empIDLabel.setText(Session.getEmployeeId());
        nameLabel.setText(Session.getName());
        deptLabel.setText(Session.getDepartment());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ClockInButton = new javax.swing.JButton();
        LeaveBalanceButton = new javax.swing.JButton();
        YearlySummaryReportButton = new javax.swing.JButton();
        ViewSalaryButton = new javax.swing.JButton();
        ApplyLeaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        empIDLabel.setText("EmployeeID");

        nameLabel.setText("Name");

        deptLabel.setText("Department");

        jLabel1.setText("Employee Main Page");

        ClockInButton.setText("Clock In");
        ClockInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockInButtonActionPerformed(evt);
            }
        });

        LeaveBalanceButton.setText("Leave Balance");
        LeaveBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveBalanceButtonActionPerformed(evt);
            }
        });

        YearlySummaryReportButton.setText("Yearly Summary Report");
        YearlySummaryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearlySummaryReportButtonActionPerformed(evt);
            }
        });

        ViewSalaryButton.setText("View Salary");
        ViewSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSalaryButtonActionPerformed(evt);
            }
        });

        ApplyLeaveButton.setText("Apply Leave");
        ApplyLeaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyLeaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(YearlySummaryReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewSalaryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LeaveBalanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClockInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ApplyLeaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empIDLabel)
                    .addComponent(deptLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deptLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ClockInButton)
                        .addGap(18, 18, 18)
                        .addComponent(ApplyLeaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(LeaveBalanceButton)
                        .addGap(18, 18, 18)
                        .addComponent(YearlySummaryReportButton)
                        .addGap(18, 18, 18)
                        .addComponent(ViewSalaryButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClockInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClockInButtonActionPerformed

    private void ApplyLeaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyLeaveButtonActionPerformed
    ApplyLeaveFormGUI leave = new ApplyLeaveFormGUI();
    leave.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ApplyLeaveButtonActionPerformed

    private void LeaveBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveBalanceButtonActionPerformed
    String input = JOptionPane.showInputDialog(this, "Enter year (e.g. 2026):");

    if (input == null) {
        return; // user pressed Cancel
    }

    input = input.trim();

    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Year cannot be empty.");
        return;
    }

    int year;
    try {
        year = Integer.parseInt(input);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid year.");
        return;
    }

    new ViewLeavesGUI(year).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_LeaveBalanceButtonActionPerformed

    private void ViewSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSalaryButtonActionPerformed
        ViewSalary view_salary = new ViewSalary();
        view_salary.setVisible(true);

        this.dispose(); 
    }//GEN-LAST:event_ViewSalaryButtonActionPerformed

    private void YearlySummaryReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearlySummaryReportButtonActionPerformed
        YearlySummaryReportGUI report = new YearlySummaryReportGUI(Session.getEmployeeId());
        report.setVisible(true);
        report.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_YearlySummaryReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Main ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyLeaveButton;
    private javax.swing.JButton ClockInButton;
    private javax.swing.JButton LeaveBalanceButton;
    private javax.swing.JButton ViewSalaryButton;
    private javax.swing.JButton YearlySummaryReportButton;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
