
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yu zi guan
 */
public class HR_Main extends javax.swing.JFrame {

    /**
     * Creates new form HR_Main
     */
    public HR_Main() {
        initComponents();
        empIDLabel.setText(Session.getEmployeeId());
        nameLabel.setText(Session.getName());
        deptLabel.setText(Session.getDepartment());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        empIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ClockInButton = new javax.swing.JButton();
        LeaveBalanceButton = new javax.swing.JButton();
        LeaveManagementButton = new javax.swing.JButton();
        PayrollManagementButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ApplyLeave = new javax.swing.JButton();
        view_salary_button = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        empIDLabel.setText("EmployeeID");

        nameLabel.setText("Name");

        deptLabel.setText("Department");

        jLabel1.setText("HR Main Page");

        ClockInButton.setText("Clock In");

        LeaveBalanceButton.setText("Leave Balance");
        LeaveBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveBalanceButtonActionPerformed(evt);
            }
        });

        LeaveManagementButton.setText("Leave Management");
        LeaveManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveManagementButtonActionPerformed(evt);
            }
        });

        PayrollManagementButton.setText("Payroll Management");
        PayrollManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayrollManagementButtonActionPerformed(evt);
            }
        });

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jButton2.setText("View Clock In");

        ApplyLeave.setText("Apply Leave");
        ApplyLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyLeaveActionPerformed(evt);
            }
        });

        view_salary_button.setText("View Salary");
        view_salary_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_salary_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empIDLabel)
                            .addComponent(deptLabel))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PayrollManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ApplyLeave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LeaveManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LeaveBalanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClockInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_salary_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(129, 129, 129))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClockInButton)
                .addGap(14, 14, 14)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(RegisterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ApplyLeave)
                .addGap(9, 9, 9)
                .addComponent(LeaveBalanceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeaveManagementButton)
                .addGap(18, 18, 18)
                .addComponent(PayrollManagementButton)
                .addGap(18, 18, 18)
                .addComponent(view_salary_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        Register registerPage = new Register();
        registerPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void LeaveBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveBalanceButtonActionPerformed
String input = JOptionPane.showInputDialog(this, "Enter year (e.g. 2026):");

    if (input == null) {
        return; // user pressed Cancel
    }

    input = input.trim();

    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Year cannot be empty.");
        return;
    }

    int year;
    try {
        year = Integer.parseInt(input);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid year.");
        return;
    }

    new ViewLeavesGUI(year).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_LeaveBalanceButtonActionPerformed

    private void ApplyLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyLeaveActionPerformed
     ApplyLeaveFormGUI leave = new ApplyLeaveFormGUI();
    leave.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ApplyLeaveActionPerformed

    private void PayrollManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayrollManagementButtonActionPerformed
        PayrollManagement dashboard = new PayrollManagement();
        dashboard.setVisible(true);

        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_PayrollManagementButtonActionPerformed

    private void view_salary_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_salary_buttonActionPerformed
        ViewSalary view_salary = new ViewSalary();
        view_salary.setVisible(true);

        this.dispose(); 
    }//GEN-LAST:event_view_salary_buttonActionPerformed

    private void LeaveManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveManagementButtonActionPerformed
                        LeaveManagementGUI lm = new LeaveManagementGUI();
                        lm.setVisible(true);
                        lm.setLocationRelativeTo(null);
                         this.dispose(); 
    }//GEN-LAST:event_LeaveManagementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HR_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HR_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HR_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HR_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HR_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyLeave;
    private javax.swing.JButton ClockInButton;
    private javax.swing.JButton LeaveBalanceButton;
    private javax.swing.JButton LeaveManagementButton;
    private javax.swing.JButton PayrollManagementButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton view_salary_button;
    // End of variables declaration//GEN-END:variables
}
