
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class PayrollManagement extends javax.swing.JFrame {

    /**
     * Creates new form PayrollManagement
     */
    public PayrollManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_payroll = new javax.swing.JButton();
        edit_payroll = new javax.swing.JButton();
        update_salary = new javax.swing.JButton();
        view_salary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_payroll.setText("Add Payroll");
        add_payroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_payrollActionPerformed(evt);
            }
        });

        edit_payroll.setText("Edit Payroll");
        edit_payroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_payrollActionPerformed(evt);
            }
        });

        update_salary.setText("Update Salary");
        update_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_salaryActionPerformed(evt);
            }
        });

        view_salary.setText("View Salary");
        view_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_salaryActionPerformed(evt);
            }
        });

        jLabel1.setText("Payroll Management");

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(back_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update_salary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_payroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit_payroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(view_salary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(add_payroll)
                .addGap(18, 18, 18)
                .addComponent(edit_payroll)
                .addGap(18, 18, 18)
                .addComponent(update_salary)
                .addGap(18, 18, 18)
                .addComponent(view_salary)
                .addGap(18, 18, 18)
                .addComponent(back_button)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_payrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_payrollActionPerformed
        PayrollManagement_Add add_payroll = new PayrollManagement_Add();
        add_payroll.setVisible(true);

        this.dispose();  
    }//GEN-LAST:event_add_payrollActionPerformed

    private void edit_payrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_payrollActionPerformed
        PayrollManagement_Edit edit_payroll = new PayrollManagement_Edit();
        edit_payroll.setVisible(true);

        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_edit_payrollActionPerformed

    private void update_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_salaryActionPerformed
        PayrollManagement_UpdateSalary update_salary = new PayrollManagement_UpdateSalary();
        update_salary.setVisible(true);

        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_update_salaryActionPerformed

    private void view_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_salaryActionPerformed
        PayrollManagement_ViewSalary view_salary = new PayrollManagement_ViewSalary();
        view_salary.setVisible(true);

        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_view_salaryActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        String dept = Session.getDepartment();

        if ("HR".equals(dept)) {
            HR_Main hrMain = new HR_Main();
            hrMain.setVisible(true);
        } else if ("Admin".equals(dept)) {
            Admin_Main adminMain = new Admin_Main();
            adminMain.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Unknown department. Logging out.");
            Login login = new Login();
            login.setVisible(true);
        }
        this.dispose(); 
      }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_payroll;
    private javax.swing.JButton back_button;
    private javax.swing.JButton edit_payroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton update_salary;
    private javax.swing.JButton view_salary;
    // End of variables declaration//GEN-END:variables
}
