/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;
import java.time.Year;

public class PayrollManagement_UpdateSalary extends javax.swing.JFrame {

    /**
     * Creates new form PayrollManagement_Update
     */
    private Service service;

    public PayrollManagement_UpdateSalary() {
        initComponents();
        this.service = Client.service;

        if (this.service == null) {
            JOptionPane.showMessageDialog(this,
                "Service not connected. Check server connection.",
                "Connection Error",
                JOptionPane.ERROR_MESSAGE);
            save_button.setEnabled(false);
            delete_button.setEnabled(false);
        }

        employeeID.setEditable(false);
        total_salary.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        search_employeeID = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        month_selection = new javax.swing.JComboBox<>();
        employeeID = new javax.swing.JTextField();
        total_salary = new javax.swing.JTextField();
        paid_status = new javax.swing.JComboBox<>();
        save_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Search Employee ID :");

        search_employeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_employeeIDActionPerformed(evt);
            }
        });

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Update Payroll Status");

        jLabel3.setText("Employee ID :");

        jLabel4.setText("Total salary of the month :");

        jLabel5.setText("Month :");

        jLabel6.setText("Status :");

        month_selection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month_selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_selectionActionPerformed(evt);
            }
        });

        paid_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unpaid", "Paid" }));

        save_button.setText("Save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(255, 102, 102));
        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(back_button)
                            .addGap(18, 18, 18)
                            .addComponent(delete_button)
                            .addGap(18, 18, 18)
                            .addComponent(save_button))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(search_employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search_button))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(month_selection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(employeeID)
                                    .addComponent(total_salary)
                                    .addComponent(paid_status, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(search_employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(total_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(month_selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(paid_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_button)
                    .addComponent(delete_button)
                    .addComponent(back_button))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_employeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_employeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_employeeIDActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        String empID = search_employeeID.getText().trim();
                if (empID.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter Employee ID");
                    return;
                }

                if (service == null) return;

                try {
                    // Get base payroll info
                    String[] payrollData = service.getPayroll(empID);
                    if (payrollData != null && payrollData.length >= 6) {
                        employeeID.setText(payrollData[0]);
                        total_salary.setText(payrollData[5]);
                    } else {
                        JOptionPane.showMessageDialog(this, "Payroll not found for Employee ID: " + empID);
                        return;
                    }

                    // Get current year status for selected month (if any)
                    int currentYear = java.time.Year.now().getValue();
                    String selectedMonth = month_selection.getSelectedItem().toString();
                    if (!selectedMonth.equals("Please select a month")) {
                        String[] statusData = service.getSalaryStatus(empID, selectedMonth, currentYear);
                        if (statusData != null && statusData.length >= 5) {
                            paid_status.setSelectedItem(statusData[3]);
                        } else {
                            paid_status.setSelectedIndex(0); // Unpaid default
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Server error: " + e.getMessage());
                }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void month_selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_selectionActionPerformed
        String empID = employeeID.getText().trim();
                String month = month_selection.getSelectedItem().toString();
                if (empID.isEmpty() || month.equals("Please select a month") || service == null) {
                    paid_status.setSelectedIndex(0);
                    return;
                }

                try {
                    int currentYear = java.time.Year.now().getValue();
                    String[] data = service.getSalaryStatus(empID, month, currentYear);
                    if (data != null && data.length >= 5) {
                        paid_status.setSelectedItem(data[3]);
                    } else {
                        paid_status.setSelectedIndex(0);
                    }
                } catch (RemoteException e) {
                    paid_status.setSelectedIndex(0);
                }
    }//GEN-LAST:event_month_selectionActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        String empID = employeeID.getText().trim();
                String salaryStr = total_salary.getText().trim();
                String month = month_selection.getSelectedItem().toString();
                String status = paid_status.getSelectedItem().toString();
                int currentYear = java.time.Year.now().getValue();

                if (empID.isEmpty() || salaryStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Employee ID and Salary cannot be empty!");
                    return;
                }
                if (month.equals("Please select a month")) {
                    JOptionPane.showMessageDialog(this, "Please select a valid month!");
                    return;
                }

                if (service == null) return;

                try {
                    double salary = Double.parseDouble(salaryStr);
                    service.saveSalaryStatus(empID, salary, month, status, currentYear);
                    JOptionPane.showMessageDialog(this, "Payroll status saved successfully!");
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid salary format!");
                } catch (RemoteException e) {
                    JOptionPane.showMessageDialog(this, "Error saving status: " + e.getMessage());
                }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        String empID = employeeID.getText().trim();
                String month = month_selection.getSelectedItem().toString();
                int currentYear = java.time.Year.now().getValue();

                if (month.equals("Please select a month")) {
                    JOptionPane.showMessageDialog(this, "Please select a valid month to delete!");
                    return;
                }

                int confirm = JOptionPane.showConfirmDialog(this,
                    "Delete this month's salary status record?",
                    "Confirm Delete",
                    JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;

                if (service == null) return;

                try {
                    service.deleteSalaryStatus(empID, month, currentYear);
                    JOptionPane.showMessageDialog(this, "Delete operation completed!");
                    month_selection.setSelectedIndex(0);
                    paid_status.setSelectedIndex(0);
                } catch (RemoteException e) {
                    JOptionPane.showMessageDialog(this, "Error deleting status: " + e.getMessage());
                }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        PayrollManagement dashboard = new PayrollManagement();
        dashboard.setVisible(true);

        this.dispose();  
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollManagement_UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollManagement_UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollManagement_UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollManagement_UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollManagement_UpdateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField employeeID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> month_selection;
    private javax.swing.JComboBox<String> paid_status;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_employeeID;
    private javax.swing.JTextField total_salary;
    // End of variables declaration//GEN-END:variables
}
